version: '3'

services:
  reverse-proxy:
    image: traefik:v2.10
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      --api=true 
      --api.dashboard=true 
      --providers.docker 
      --providers.docker.network="web"
      --providers.file.directory=/config/
      --providers.file.watch=true
      --entrypoints.web-secure.address=:443
      --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "443:443"
      # - "9000:9000"
      # - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/config
    networks:
      - web
    restart: unless-stopped
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik-1.federation.home`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/config/usersfile"
      - "traefik.http.routers.api.tls=true"

networks: 
  web:
    external: true
