[[tls.certificates]]
  certFile = "/config/federation.crt"
  keyFile = "/config/federation.key"

[tls.stores]
  [tls.stores.default]
   [tls.stores.default.defaultCertificate]
      certFile = "/config/federation.crt"
      keyFile = "/config/federation.key"
